# Generated by Django 3.1.4 on 2020-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_auto_20201203_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
