# Generated by Django 3.1.4 on 2020-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0003_auto_20201203_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_mark',
            field=models.BooleanField(default=False),
        ),
    ]
