# Generated by Django 3.1.4 on 2020-12-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0004_source_is_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='is_mark',
            new_name='marked',
        ),
    ]
